#festory.py
#You Zhou
#prints storylines for Fire Emblem: Alex Legion
import time
def prologueStory(name):
    print("""+=======FIRE EMBLEM=======+
+-----The Alex Legion-----+
+By You Zhou              +""")
    a = input()
    print("Long ago, the land of Randonia was ruled by the kingdom of randomness.")
    a = input()
    print("The man who started this kingdom was named King You Zhou I.")
    a = input()
    print("After 17 generations of rule, someone disapproved of the You Zhou rule.")
    a = input()
    print("That man's name was Alex.")
    a = input()
    print("He believed that not all creatures should be equal")
    a = input()
    print("You see, the kingdom of You Zhou treated dragons as equals to humans")
    a = input()
    print("Alex disagreed with this, and thus started the 'Alex Rebellion'")
    a = input()
    print("All who joined him renamed themselves Alex or Alexa and massacred 14 of the 15 major cities people and lords.")
    a = input()
    print("The fifteenth city, Leadia, the capital was almost completely massacred")
    a = input()
    print("Prince You Zhou XVII managed to escape along with a few trustworthy helpers")
    a = input()
    print("However Alex bandits followed them and seperated You Zhou from his allies")
    a = input()
    print("You Zhou found a man unconcsious in the woods of Leadia...")
    a = input()
    print("""     PROLOGUE
--------------------
A man in the woods""")
    print("???: Hello? Sir are you awake?")
    a = input()
    print(name," Huh? Where am I?",sep=":")
    a = input()
    print("You Zhou XVII: I found you sleeping here. I'm Prince You Zhou XVII, but call me Yoyo")
    if name.lower() == "you zhou":
        print(name," Lel my name is also You Zhou. Btw how r u a prince",sep=":")
    else:
        print(name," Prince of where? I never heard of you.",sep=":")
    a = input()
    print("Yoyo: Huh? You never heard of the You Zhou kingdom? It was only taken - wait! You're not an Alex are you!?")
    a = input()
    if name.lower() == "alex":
        print(name," Well, my name is Alex, but I don't see how that's a bad thing",sep=":")
    else:
        print(name,": No, I am ",name,sep="")
    a = input()
    print("Yoyo: Oh good, you're not one of them. They killed my family... [rip] (kek) (lol)")
    a = input()
    print("???: Hehehe! Finally found you pampered brat! Prepare to die!")
    a = input()
    print("*Bandits flood the fields*")
    a = input()
    print("Yoyo: Crap! There's so many! Stay behind me! I'll take them on!")
    a = input()
    print(name," No it's fine. I can fight too!",sep=":")
    a = input()
    print("Yoyo: Alright then! But don't get yourself killed!")
    time.sleep(1)
    print("==============PLAYER PHASE================")
    print("Defeat all enemies!")
    
def chapter1Story(name):
    print("Yoyo: Thank goodness... we fought them off. I really couldn't have done it without you",name)
    a = input()
    print("Yoyo: Alright! Let's find the allies I got seperated from. They should be in Hypobrit.")
    a = input()
    print("...And so the 2 heroes leave for Hypobrit, a small town near Leadia, hoping that it was free of the Alex Legion")
    a = input()
    print("The kingdom of Randomness divided the land of Randonia into 15 cities: Leadia, Crazewell, Angrae, Sadana, Depreford, Intelierde, Tryhardion, Religelet, Condescen, Poetern, Litia, Tradaus, Insulria, Sadistaruz and Impatorde")
    a = input()
    print("The Alex Legion has already suceeded in taking over all 15, but have not completely massacred Leadia's people.")
    a = input()
    print("Yoyo is now going to meet up where he planned to with his trusty crew")
    a = input()
    print(name,"and Yoyo head towards Hypobrit...")
    a = input()
    print("""    Chapter 1
-----------------
A revolution to a revolution""")
    a = input()
    print("Yoyo: We should be there soon... Ah! Thank goodness! The crew is there!")
    a = input()
    print("???: HEY! Lord You! We're so sorry for letting you get split up... those bandits... were very effective")
    a = input()
    print("Yoyo: Don't worry Francisco. This man helped me. His name is",name)
    a = input()
    print("Francisco: Pleasure to meet you",name,". I thank you for protecting our Lord You Zhou... My name is Francisco Mateos Alarcon IV - a Cavalier in training, but you can call me Francisco Mateos Alarcon")
    a = input()
    print("???: Nah just call him Franny")
    a = input()
    print(name,": Franny?",sep="")
    a = input()
    print("???: Yeah, that's what I call him. I'm Gary - the Wandering Axe-man, by the way")
    a = input()
    print("Franny: Thanks a lot Gary... I told you not to pass that nickname around!")
    a = input()
    print("Gary: *kek*")
    a = input()
    print("Yoyo: Er... well this transporter is Henning. He's one of my only surviving helpers and carries our stuff.")
    a = input()
    print("Henning: Hello Mister!!")
    a = input()
    print("Yoyo: ...And this paladin is Sir Albert. He's an experienced soldier in Leadia. However, he's the only veteran soldier who survived")
    a = input()
    print("Albert: Hello lad. Pretty good at fighting eh?")
    a = input()
    print(name,": Thank you sir.",sep="")
    a = input()
    print("Albert: Okay, now that the Lord is back, I suggest we seek some help... in this crisis... our only chance would be the Divine Forgeries")
    a = input()
    print("Yoyo: Ah yes. I didn't inform our friend here.")
    a = input()
    print(name,": I am rather curious. What are these Divine Forgeries?",sep="")
    a = input()
    print("Albert: The first King, Lord You Zhou I, fought off the evil demons of this land and banished them to te Underworld using the Divine Light tome, Borealibur, and the Sword of Smiting, Durandal")
    a = input()
    print("Albert: The other 6 weapons were used by his companions. They included the Divine Flame tome, Upperworld Fire, the dark tome of Death's Shadow, Inifite Abyss, the Piercing Spear, Sparken, the Axe of Destruction, Ravager, the Heavenly Blade, Excalibur and the Bow of Spirits, Doom Spiraller.")
    a = input()
    print("Yoyo: We are going to find them to defeat Alex. Since our numbers are limited powerful weapons are required.")
    a = input()
    print("Albert: They are located at the Sacred Isle...")
    a = input()
    print("???: Ha! Found you! We got you outnumbered... prepare to die!")
    a = input()
    print("*Bandits flood the field*")
    a = input()
    print("Albert: Everyone! We must protect Lord You Zhou!")
    a = input()
    print("Yoyo: Ready",name,"? Let's do this!")
    time.sleep(1)
    print("==============PLAYER PHASE================")
    print("Defeat all enemies!")
